Models/Result.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.Data.SqlClient.DataClassification;

namespace onlineexamproject.Models
{
    public class Result
    {
        [Key]
        public int  ResultId { get; set; }

        [Required]
        public int Student_Id { get; set; }

        [Required]
        public int  ExamId { get; set; }

        [Required]
        [Range (0,int.MaxValue,ErrorMessage ="Score cannot be negative")]
        public int Score { get; set; }

    }
}

Models/ResultView.cs
using System.Collections.Generic;
namespace onlineexamproject.Models
{
    public class ResultView
    {
        public List<StudentChoice>? StudentChoices { get; set; }
        public List<Questions>? OriginalAnswers { get; set; }
        public int Student_Id { get; set; }
        public int ExamId { get; set; }
        public float Percentage { get; set; }
    }
}

Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using onlineexamproject.Data;
using onlineexamproject.Models;

namespace onlineexamproject.Controllers
{
    public class CourseController : BaseController
    {
        private readonly IConfiguration _configuration;

        public CourseController(IConfiguration configuration)
        {
            this._configuration = configuration;
        }

        // GET: Course
        public IActionResult Index()
        {
            DataTable dtbl = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("CourseAll", sqlConnection);
                sqlDa.SelectCommand.CommandType = CommandType.StoredProcedure;
                sqlDa.Fill(dtbl);
            }
            return View(dtbl);
        }

        // GET: Course/AddorEdit/
        public IActionResult AddorEdit(int? id)
        {
            Course course = new Course();
            if(id > 0)
            {
                course = FetchCourseById(id);
            }
            return View(course);
        }

        // POST: Course/AddorEdit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddorEdit(int id, [Bind("Course_Id,Course_Name,Course_Description")] Course course)
        {

            if (ModelState.IsValid)
            {
                using(SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
                {
                    sqlConnection.Open();
                    SqlCommand sqlCmd = new SqlCommand("CourseAddorEdit", sqlConnection);
                    sqlCmd.CommandType = CommandType.StoredProcedure;
                    sqlCmd.Parameters.AddWithValue("Course_Id", course.Course_Id);
                    sqlCmd.Parameters.AddWithValue("Course_Name", course.Course_Name);
                    sqlCmd.Parameters.AddWithValue("Course_Description", course.Course_Description);
                    sqlCmd.ExecuteNonQuery();
                }
               
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Course/Delete/5
        public IActionResult Delete(int? id)
        {
           Course course = FetchCourseById(id);
            return View(course);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                SqlCommand sqlCmd = new SqlCommand("CourseDeleteById", sqlConnection);
                sqlCmd.CommandType = CommandType.StoredProcedure;
                sqlCmd.Parameters.AddWithValue("Course_Id",id);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction(nameof(Index));
        }

        [NonAction]
        public Course FetchCourseById(int? id)
        {
             Course course = new Course();

            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                DataTable dtbl = new DataTable();
                sqlConnection.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("CourseById", sqlConnection);
                sqlDa.SelectCommand.CommandType = CommandType.StoredProcedure;
                sqlDa.SelectCommand.Parameters.AddWithValue("Course_Id", id);
                sqlDa.Fill(dtbl);
                if (dtbl.Rows.Count == 1)
                {
                    course.Course_Id = Convert.ToInt32(dtbl.Rows[0]["Course_Id"].ToString());
                    course.Course_Name = dtbl.Rows[0]["Course_Name"].ToString();
                    course.Course_Description = dtbl.Rows[0]["Course_Description"].ToString();

                }
                return course;
            }
        }
    }
}

Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using onlineexamproject.Data;
using onlineexamproject.Extensions;
using onlineexamproject.Models;

namespace onlineexamproject.Controllers
{
    public class ResultController : BaseController
    {
        private readonly IConfiguration _configuration;

        public ResultController(IConfiguration configuration)
        {
            this._configuration = configuration;
        }

        public IActionResult All()
        {
            User? sessionUser = HttpContext.Session.GetObjectFromJson<User>("sessionUser");
            if (sessionUser == null)
            {
                return RedirectToAction("Student", "Login");
            }

            int studentId = sessionUser.Id;

            DataTable dtbl = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("StudentResultsById", sqlConnection);
                sqlDa.SelectCommand.CommandType = CommandType.StoredProcedure;
                sqlDa.SelectCommand.Parameters.AddWithValue("@StudentId", studentId);
                sqlDa.Fill(dtbl);
            }
            return View(dtbl);
        }

        // GET: Result
        public IActionResult Index()
        {
            DataTable dtbl = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("ResultAll", sqlConnection);
                sqlDa.SelectCommand.CommandType = CommandType.StoredProcedure;
                sqlDa.Fill(dtbl);

            }
            return View(dtbl);
        }

        // GET: Result/Edit/5
        public IActionResult Edit(int? id)
        {
            Result result = new Result();
            if(id > 0)
            {
                result = FetchResultById(id);
            }
            return View(result);
        }

        // POST: Result/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("ResultId,Student_Id,ExamId,Score")] Result result)
        {
            

            if (ModelState.IsValid)
            {
                using (SqlConnection sqlConnection= new SqlConnection(_configuration.GetConnectionString("DevConnection")))
                {
                    sqlConnection.Open();
                    SqlCommand sqlCmd =  new SqlCommand("ResultEdit",sqlConnection);
                    sqlCmd.CommandType = CommandType.StoredProcedure ;
                    sqlCmd.Parameters.AddWithValue("ResultId", result.ResultId);
                    sqlCmd.Parameters.AddWithValue("Student_Id", result.Student_Id); 
                    sqlCmd.Parameters.AddWithValue("ExamId", result.ExamId);
                    sqlCmd.Parameters.AddWithValue("Score", result.Score);
                    sqlCmd.ExecuteNonQuery();
                }
                
                return RedirectToAction(nameof(Index));
            }
            return View(result);
        }

        [NonAction]
        public Result FetchResultById(int? id)
        {
            Result result = new Result();
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                DataTable dtbl = new DataTable();
                sqlConnection.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("ResultById", sqlConnection);
                sqlDa.SelectCommand.CommandType = CommandType.StoredProcedure;
                sqlDa.SelectCommand.Parameters.AddWithValue("ResultId", id);
                sqlDa.Fill(dtbl);
                if (dtbl.Rows.Count == 1)
                {
                    result.ResultId = Convert.ToInt32(dtbl.Rows[0]["ResultId"].ToString());
                    result.Student_Id = Convert.ToInt32(dtbl.Rows[0]["Student_Id"].ToString());
                    result.ExamId = Convert.ToInt32(dtbl.Rows[0]["ExamId"].ToString());
                    result.Score = (int)Convert.ToDouble(dtbl.Rows[0]["Score"].ToString());
                }
                return result;
            }
        }





        public IActionResult Result(int examId)
        {
            
            try
            {
                User? sessionUser = HttpContext.Session.GetObjectFromJson<User>("sessionUser");
                if (sessionUser == null)
                {
                    return RedirectToAction("Student", "Login");
                }

                int student_Id = sessionUser.Id;

                List<StudentChoice> studentChoices = GetStudentChoices(student_Id, examId);
                if (studentChoices == null || studentChoices.Count == 0)
                {
                    return RedirectToAction("StudentDashboard", "StudentDashboard");
                }

                List<Questions> question = GetQuestions(examId);
                float percentage = GetResult(studentChoices, question);

                var resultViewModel = new ResultView
                {
                    StudentChoices = studentChoices,
                    OriginalAnswers = question,
                    ExamId = examId,
                    Student_Id = student_Id,
                    Percentage = percentage
                };
                bool StoreResultStatus = StoreResult(student_Id, examId, percentage);

                return View(resultViewModel);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return View("Error");
            }
        }

        private float GetResult(List<StudentChoice> studentChoices, List<Questions> correctAns)
        {
            float totalQuestions = correctAns.Count;
            float correctAnswers = 0;

            foreach (var choice in studentChoices)
            {
                var correctAnswer = correctAns.Find(q => q.Q_Id == choice.Q_Id)?.Correct_Answer;
                if (correctAnswer == choice.OptionSelected)
                {
                    correctAnswers++;
                }
            }

            if (totalQuestions == 0) return 0;
            float result = (correctAnswers * 100) / totalQuestions;
            return result;
        }

        private List<StudentChoice> GetStudentChoices(int student_Id, int examId)
        {
            List<StudentChoice> choices = new List<StudentChoice>();
            string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True;";
            string query = "SELECT * FROM StudentChoice WHERE Student_Id=@Student_Id AND ExamId=@ExamId";

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        command.Parameters.AddWithValue("@Student_Id", student_Id);
                        command.Parameters.AddWithValue("@ExamId", examId);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                int questionId = reader.GetInt32(reader.GetOrdinal("Q_Id"));
                                string optionSelected = reader.GetString(reader.GetOrdinal("OptionSelected"));

                                StudentChoice choice = new StudentChoice
                                {
                                    Student_Id = student_Id,
                                    ExamId = examId,
                                    Q_Id = questionId,
                                    OptionSelected = optionSelected
                                };
                                choices.Add(choice);
                            }
                        }
                    }
                }
                catch (SqlException ex)
                {
                    Console.WriteLine(ex.ToString());
                }
            }

            return choices;
        }

        private List<Questions> GetQuestions(int examId)
        {
            List<Questions> questions = new List<Questions>();
            string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True;";
            string query = "SELECT * FROM Questions WHERE ExamId=@ExamId";

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        command.Parameters.AddWithValue("@ExamId", examId);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {

Views/Result/All.cshtml
@model System.Data.DataTable

@{
    ViewData["Title"] = "All Results";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <link href="~/css/dashboard.css" rel="stylesheet">

    <style>
        .center {
            text-align: center;
            vertical-align: middle;
            line-height: 90px;
        }

        table{
            margin-left:40px;
        }

        .button-container {
            margin-left: 50px;
            display: flex;
            gap: 900px;
        }

        .custom-button {
            width: 180px; /* Set width */
            height: 50px; /* Set height */
            background-color: #55AD9B; /* Change background color */
            color: white; /* Change text color */
            font-size: 16px; /* Increase font size */
            cursor: pointer; /* Change cursor on hover */
            border-radius: 5px;
        }

    </style>
</head>
<body>
    <div class="head1">
        <div class="head">
            <div class="side-nav">
                <img src="~/images/logo.png" height="50px" width="90px" />
                <div class="user">
                    <img src="~/images/profile-pic.png" class="user-img">
                    <div>
                        <strong>Username:</strong> @ViewBag.Username<br>
                        <strong>User ID:</strong> @ViewBag.Id
                    </div>
                    <img src="~/images/star.png" class="star-png">
                </div>
                <ul>
                    <li class="hover"><img src="~/images/dashboard.png"><p><a asp-area="" asp-controller="StudentDashboard" asp-action="StudentDashboard" style="color: #F1F8E8; text-decoration:none">DashBoard</a></p></li>
                    <li class="hover"><img src="~/images/result.png"><p><a asp-area="" asp-controller="Result" asp-action="All" style="color: #F1F8E8; text-decoration:none">Result</a></p></li>
                </ul>

                <ul>
                    <li style="color:white;"><img src="~/images/logout.png"><p><a asp-area="" asp-controller="Home" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Log Out</a></p></li>
                </ul>
            </div>
        <!-- Your sidebar and navigation links -->
        <div class="main-body">
            <h1 class="text-center">@ViewData["Title"]</h1>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Result Id</th>
                        <th>Exam Id</th>
                        <th>Score</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (System.Data.DataRow row in Model.Rows)
                    {
                        <tr>
                            <td>@row["ResultId"]</td>
                            <td>@row["ExamId"]</td>
                            <td>@row["Score"]</td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="center">
                @using (Html.BeginForm("StudentDashboard", "StudentDashboard"))
                {
                    <button asp-action="StudentDashboard" asp-controller="StudentDashboard" class="btn btn-primary" type="submit" style="background-color:#55AD9B;color:white;border-color:#4B9C8A">Back to Dashboard</button>
                }
            </div>
        </div>
    </div>
</body>
</html>

Views/Result/Edit.cshtml
@model onlineexamproject.Models.Result

@{
    ViewData["Title"] = "Edit Result";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href='~/css/dashboard.css' rel='stylesheet'>
    <style>
        .box-center {
            width: 300px;
            margin: 5vh auto 5vh auto;
            margin-top: 70px;
            background: transparent;
            border-radius: 4px;
            font-size: 1rem;
            position: relative;
            width: 500px;
            backdrop-filter: blur(25px);
            border: 2px solid var(--primary-color);
            border-radius: 15px;
            padding: 2em 2em 3em 2em;
            color: var(--second-color);
            box-shadow: 0px 0px 10px 2px rgba(0,0,0,0.2);
            background-color: #F1F8E8;
        }

        .btn {
            margin: 10px;
        }

        .form-group {
            padding: 10px;
        }
    </style>
</head>

<body>
    <div class="head">
        <div class="side-nav">
            <img src="~/images/logo.png" height="50px" width="90px" />
            <div class="user">
                <img src="~/images/profile-pic.png" class="user-img">
                <div>
                    <strong>Username:</strong> @ViewBag.Username<br>
                    <strong>User ID:</strong> @ViewBag.Id
                </div>
                <img src="~/images/star.png" class="star-png">
            </div>
            <ul>
                <li class="hover"><img src="~/images/dashboard.png"><p><a asp-area="" asp-controller="TeacherDashboard" asp-action="TeacherDashboard" style="color: #F1F8E8; text-decoration:none">DashBoard</a></p></li>
                <li class="hover"><img src="~/images/course.png"><p><p><a asp-area="" asp-controller="Course" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Add Course</a></p></li>
                <li class="hover"><img src="~/images/exam.png"><p><a asp-area="" asp-controller="Exam" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Add Exam</a></p></li>
                <li class="hover"><img src="~/images/test.png"><p><a asp-area="" asp-controller="Questions" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Add Questions</a></p></li>
                <li class="hover"><img src="~/images/result.png"><p><a asp-area="" asp-controller="Result" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Result</a></p></li>
            </ul>

            <ul>
                <li style="color:white;"><img src="~/images/logout.png"><p><a asp-area="" asp-controller="Home" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Log Out</a></p></li>
            </ul>
        </div>
        <div class="main-body">
            <div class="box-center">

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-asp-controller="Result">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ResultId" />
            <div class="form-group">
                <label asp-for="Student_Id" class="control-label"></label>
                <input asp-for="Student_Id" class="form-control" />
                <span asp-validation-for="Student_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamId" class="control-label"></label>
                <input asp-for="ExamId" class="form-control" />
                <span asp-validation-for="ExamId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Score" class="control-label"></label>
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>



            </div>
        </div>
    </div>
</body>
</html>


Views/Result/Index.cshtml
@model System.Data.DataTable

@{
    ViewData["Title"] = "Result of All Students";
}



<style>
    a {
        text-decoration: none;
    }

    table {
        margin-top: 50px;
        margin-left: 50px;
    }
</style>



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href='~/css/dashboard.css' rel='stylesheet'>
</head>

<body>
    <div class="head">
        <div class="side-nav">
            <img src="~/images/logo.png" height="50px" width="90px" />
            <div class="user">
                <img src="~/images/profile-pic.png" class="user-img">
                <div>
                    <strong>Username:</strong> @ViewBag.Username<br>
                    <strong>User ID:</strong> @ViewBag.Id
                </div>
                <img src="~/images/star.png" class="star-png">
            </div>
            <ul>
                <li class="hover"><img src="~/images/dashboard.png"><p><a asp-area="" asp-controller="TeacherDashboard" asp-action="TeacherDashboard" style="color: #F1F8E8; text-decoration:none">DashBoard</a></p></li>
                <li class="hover"><img src="~/images/course.png"><p><p><a asp-area="" asp-controller="Course" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Add Course</a></p></li>
                <li class="hover"><img src="~/images/exam.png"><p><a asp-area="" asp-controller="Exam" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Add Exam</a></p></li>
                <li class="hover"><img src="~/images/test.png"><p><a asp-area="" asp-controller="Questions" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Add Questions</a></p></li>
                <li class="hover"><img src="~/images/result.png"><p><a asp-area="" asp-controller="Result" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Result</a></p></li>
            </ul>

            <ul>
                <li style="color:white;"><img src="~/images/logout.png"><p><a asp-area="" asp-controller="Home" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Log Out</a></p></li>
            </ul>
        </div>
        <div class="main-body">

            <h1 class="text-center">@ViewData["Title"]</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                Student Id
            </th>
            <th>
                Exam Id
            </th>
            <th>
               Score
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
     @for (int i = 0; i < Model.Rows.Count; i++) 
     {
        <tr>
            <td>
                @Model.Rows[i]["StudentId"]
            </td>
            <td>
                @Model.Rows[i]["ExamId"]
            </td>
            <td>
               @Model.Rows[i]["Score"]
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@Model.Rows[i]["ResultId"]">Edit</a>
            </td>
        </tr>
}
    </tbody>
</table>

        </div>
     </div>
</body>
</html>