Models/Signup.cs
namespace onlineexamproject.Models;
public class Signup
{
    public required string Username { get; set; }
    public required string Password { get; set; }
    public required string ConfirmPassword { get; set; }
    public bool RememberMe { get; set; }
}

Models/Student.cs
namespace onlineexamproject.Models;

// class to send objects to and from database
public class Student
{
    public required string Username { get; set; }
    public required string Password { get; set; }
    public required int Student_Id { get; set; }
}

Models/Teacher.cs
namespace onlineexamproject.Models;

// class to send objects to and from database
public class Teacher
{
    public required string Username { get; set; }
    public required string Password { get; set; }
    public required int TeacherId { get; set; }
}

Controllers/LoginController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using onlineexamproject.Models;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Data;
using onlineexamproject.Extensions;

namespace onlineexamproject.Controllers
{
    public class LoginController : BaseController
    {
        private readonly ILogger<LoginController> _logger;
        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }

        public IActionResult StudentDashboard()
        {
            return View();
        }

        public IActionResult TeacherDashboard()
        {
            return View();
        }

        public IActionResult Student()
        {
            return View();
        }

        public IActionResult Teacher()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public bool dbAuthStudent(string Username, string Password)
        {
            string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True;";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();

                    string query = "SELECT * FROM Student WHERE username=@username AND password=@password";
                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        command.Parameters.AddWithValue("@username", Username);
                        command.Parameters.AddWithValue("@password", Password);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.HasRows)
                            { 

                                return true;
                            }
                            else
                            {
                                return false;
                            }
                        }
                    }
                }
                catch (SqlException ex)
                {
                    Console.WriteLine(ex.ToString());
                    return false;
                }
            }
        }

        public bool dbAuthTeacher(string Username, string Password)
        {
            string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True;";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();

                    string query = "SELECT  * FROM Teacher WHERE username=@username AND password=@password";
                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        command.Parameters.AddWithValue("@username", Username);
                        command.Parameters.AddWithValue("@password", Password);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.HasRows)
                            {
                                return true;
                            }
                            else
                            {
                                return false;
                            }
                        }
                    }
                }
                catch (SqlException ex)
                {
                    Console.WriteLine(ex.ToString());
                    return false;
                }
            }
        }

        [HttpPost]
        public IActionResult Student(Login loginModel)
        {
            if (ModelState.IsValid)
            {
                if (dbAuthStudent(loginModel.Username, loginModel.Password))
                {

                    string uname = loginModel.Username;
                    User sessionUser = new User(uname, "Student", 0); // Set Id to a placeholder (0)
                    int Student_Id = sessionUser.getId(loginModel.Username); // Use loginModel.Username after creation
                    sessionUser.Id = Student_Id; // Update Id after retrieval
                    HttpContext.Session.SetObjectAsJson("sessionUser",sessionUser);

                    ViewBag.Username = sessionUser.Username;
                    ViewBag.Id = sessionUser.Id;

                    return RedirectToAction("StudentDashboard", "StudentDashboard");
                    //return Redirect("StudentSuccesss");

                    //return Redirect("StudentDashboard");
                }
                else
                {
                    ModelState.AddModelError("", "Wrong username or password.");
                }
            }
            return View(loginModel);
        }

        [HttpPost]
        public IActionResult Teacher(Login loginModel)
        {
            if (ModelState.IsValid)
            {
                if (dbAuthTeacher(loginModel.Username, loginModel.Password))
                {

                    string uname = loginModel.Username;
                    User sessionUser = new User(uname, "Teacher", 0); // Set Id to a placeholder (0)
                    int TeacherId = sessionUser.getId(loginModel.Username); // Use loginModel.Username after creation
                    sessionUser.Id = TeacherId; // Update Id after retrieval
                    HttpContext.Session.SetObjectAsJson("sessionUser", sessionUser);

                    ViewData["Username"] = sessionUser.Username;
                    ViewData["Id"] = sessionUser.Id;

                    return View("~/Views/TeacherDashboard/TeacherDashboard.cshtml");
                    //return View("TeacherDashboard");


                }
                else
                {
                    ModelState.AddModelError("", "Invalid username or password.");
                }
            }
            return View(loginModel);
        }

    }
}

Controllers/SignupController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using onlineexamproject.Models;
using System.Text.RegularExpressions;
//using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data.SqlClient;

namespace onlineexamproject.Controllers;

public class SignupController : BaseController
{
    private readonly ILogger<SignupController> _logger;

    public SignupController(ILogger<SignupController> logger)
    {
        _logger = logger;
    }




    public IActionResult Student()
    {
        return View();
    }

    public IActionResult Teacher()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public bool validPassword(string pwd)
    {
        const int MinimumLength = 8;
        const int MaximumLength = 16;
        const string UpperCasePattern = @"[A-Z]";
        const string LowerCasePattern = @"[a-z]";
        const string DigitPattern = @"\d";
        const string SpecialCharacterPattern = @"[!@#$%^&*(),.?:{}|<>]";
        if (string.IsNullOrWhiteSpace(pwd))
        {
            return false;
        }

        if (pwd.Length < MinimumLength || pwd.Length > MaximumLength)
        {
            return false;
        }

        if (!Regex.IsMatch(pwd, UpperCasePattern))
        {
            return false;
        }

        if (!Regex.IsMatch(pwd, LowerCasePattern))
        {
            return false;
        }

        if (!Regex.IsMatch(pwd, DigitPattern))
        {
            return false;
        }

        if (!Regex.IsMatch(pwd, SpecialCharacterPattern))
        {
            return false;
        }
        return true;
    }

    public bool uniqueStudentUsername(string username)
    {
        string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True;";
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            try
            {
                connection.Open();

                string query = "SELECT Username FROM Student WHERE username=@username";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@username", username);
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            return false;
                        }
                        else
                        {
                            return true;
                        }
                    }
                }
            }
            catch (SqlException ex)
            {
                Console.WriteLine(ex.ToString());
                return false;
            }
        }
    }

    public bool AddStudentEntry(string username, string password)
    {
        string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True";
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            try
            {
                connection.Open();
                string query = "INSERT INTO Student (Username, Password) values (@username, @password)";
                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@username", username);
                command.Parameters.AddWithValue("@password", password);
                command.ExecuteNonQuery();
                return true;
            }
            catch (SqlException ex)
            {
                Console.WriteLine(ex.ToString());
                return false;
            }
        }
    }

    [HttpPost]
    public IActionResult Student(Signup signupModel)
    {
        if (ModelState.IsValid)
        {
            if (signupModel.ConfirmPassword == signupModel.Password
                && uniqueStudentUsername(signupModel.Username)
                && validPassword(signupModel.Password))
            {
                AddStudentEntry(signupModel.Username, signupModel.Password);
                return View("~/Views/Login/Student.cshtml");
            }
            else
            {
                if (uniqueStudentUsername(signupModel.Username) != true)
                {
                    ModelState.AddModelError("", "Username already taken.");
                }
                else if (validPassword(signupModel.Password) != true)
                {
                    ModelState.AddModelError("", "Password is not strong enough!");
                }
                else
                {
                    ModelState.AddModelError("", "Passwords do not match.");
                }
            }
        }
        return View("Student");
    }

    public bool AddTeacherEntry(string username, string password)
    {
        string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True";
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            try
            {
                connection.Open();
                string query = "INSERT INTO Teacher (Username, Password) values (@username, @password)";
                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@username", username);
                command.Parameters.AddWithValue("@password", password);
                command.ExecuteNonQuery();
                return true;
            }
            catch (SqlException ex)
            {
                Console.WriteLine(ex.ToString());
                return false;
            }
        }
    }

    public bool uniqueTeacherUsername(string username)
    {
        string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True";
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            try
            {
                connection.Open();

                string query = "SELECT Username FROM Teacher WHERE username=@username";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@username", username);
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            return false;
                        }
                        else
                        {
                            return true;
                        }
                    }
                }
            }
            catch (SqlException ex)
            {
                Console.WriteLine(ex.ToString());
                return false;
            }
        }
    }

    [HttpPost]
    public IActionResult Teacher(Signup signupModel)
    {
        if (ModelState.IsValid)
        {
            if (signupModel.ConfirmPassword == signupModel.Password
                && uniqueStudentUsername(signupModel.Username)
                && validPassword(signupModel.Password))
            {
                AddTeacherEntry(signupModel.Username, signupModel.Password);
                return View("~/Views/Login/Teacher.cshtml");
            }
            else
            {
                if (uniqueTeacherUsername(signupModel.Username) != true)
                {
                    ModelState.AddModelError("", "Username already taken.");
                }
                else if (validPassword(signupModel.Password) != true)
                {
                    ModelState.AddModelError("", "Password is not strong enough!");
                }
                else
                {
                    ModelState.AddModelError("", "Passwords do not match.");
                }
            }
        }
        return View("Teacher");
    }
}

Views/Signup/Student.cshtml
@model onlineexamproject.Models.Signup

<html>
<head>
    <title>Student SignUp</title>

    <style>
        body {
            
            background-position: center;
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            font-family: 'Poppins', sans-serif;
            color: black;
            background-color: #D8EFD3;
        }

        #form {
            width: 300px;
            margin: 5vh auto 5vh auto;
            margin-top: 70px;
            background: transparent;
            border-radius: 4px;
            font-size: 1rem;
            position: relative;
            width: 450px;
            backdrop-filter: blur(25px);
            border: 2px solid var(--primary-color);
            border-radius: 15px;
            padding: 2em 2em 3em 2em;
            color: var(--second-color);
            box-shadow: 0px 0px 10px 2px rgba(0,0,0,0.2);
            background-color: #F1F8E8;
        }

            #form h1 {
                font-size: 2rem;
                color: black;
                text-align: center;
            }

            #form button {
                padding: 10px;
                margin-top: 10px;
                width: 100%;
                color: white;
                background-color: #55AD9B;
                border: none;
                border-radius: 4px;
                font-size: 1rem;
            }



        .input-control {
            display: flex;
            padding-right: 20px;
            flex-direction: column;
        }

            .input-control input {
                border: 2px solid #f0f0f0;
                border-radius: 4px;
                display: block;
                font-size: 12px;
                padding: 10px;
                width: 100%;
            }

                .input-control input:focus {
                    outline: 0;
                }

            .input-control.success input {
                border-color: #09c372;
            }

            .input-control.error input {
                border-color: #ff3860;
            }

            .input-control .error {
                color: #ff3860;
                font-size: 9px;
                height: 13px;
            }

            .form-group{
                padding:10px;
            }

        .login {
            padding: 20px;
            text-align: center;
            font-size:1em;
        }
    </style>

</head>
<body>
<div class="container">
        <form method="post" asp-action="Student" asp-controller="Signup" id="form" >
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <h1>Student Sign Up</h1>

          <div class="input-control">
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                    <input asp-for="Username" class="form-control" placeholder="Username" autocomplete="off" />
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" type="password" placeholder="Password" autocomplete="off" />
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                    <input asp-for="ConfirmPassword" class="form-control" type="password" placeholder="Confirm Password" autocomplete="off" />
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>

            </div>

                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="RememberMe" type="checkbox"> Remember Me
                        </label>
                    </div>
                </div>

                

         
            <button type="submit" class="btn btn-primary">Sign Up</button>
            <div class="login">
                <p >Already registered? <a asp-controller="Login" asp-action="Student">Log In</a></p>
            </div>
            
        </form>
        
    </div>
</body>
</html>

Views/Signup/Teacher.cshtml
@model onlineexamproject.Models.Signup

<html>
<head>
    <title>Teacher SignUp</title>

    <style>
        body {
            background-position: center;
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            font-family: 'Poppins', sans-serif;
            color: black;
            background-color: #D8EFD3;
        }

        #form {
            width: 300px;
            margin: 5vh auto 5vh auto;
            margin-top:70px;
            background: transparent;
            border-radius: 4px;
            font-size: 1rem;
            position: relative;
            width: 450px;
            backdrop-filter: blur(25px);
            border: 2px solid var(--primary-color);
            border-radius: 15px;
            padding: 2em 2em 3em 2em;
            color: var(--second-color);
            box-shadow: 0px 0px 10px 2px rgba(0,0,0,0.2);
            background-color: #F1F8E8;
        }

            #form h1 {
                font-size: 2rem;
                color: black;
                text-align: center;
            }

            #form button {
                padding: 10px;
                margin-top: 10px;
                width: 100%;
                color: white;
                background-color: #55AD9B;
                border: none;
                border-radius: 4px;
                font-size: 1rem;
            }



        .input-control {
            display: flex;
            padding-right: 20px;
            flex-direction: column;
        }

            .input-control input {
                border: 2px solid #f0f0f0;
                border-radius: 4px;
                display: block;
                font-size: 12px;
                padding: 10px;
                width: 100%;
            }

                .input-control input:focus {
                    outline: 0;
                }

            .input-control.success input {
                border-color: #09c372;
            }

            .input-control.error input {
                border-color: #ff3860;
            }

            .input-control .error {
                color: #ff3860;
                font-size: 9px;
                height: 13px;
            }

        .form-group {
            padding: 10px;
        }

        .login {
            padding: 20px;
            text-align: center;
            font-size: 1em;
        }
    </style>

</head>
<body>


<div class="container">
    
        <form method="post" asp-action="Teacher" asp-controller="Signup" id="form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <h1>Teacher Sign Up</h1>
                <div class="input-control">

            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                    <input asp-for="Username" class="form-control" placeholder="Username" autocomplete="off" />
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" type="password" placeholder="Password" autocomplete="off" />
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                    <input asp-for="ConfirmPassword" class="form-control" type="password" placeholder="Confirm Password" autocomplete="off" />
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>

            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="RememberMe" type="checkbox"> Remember Me
                    </label>
                </div>
            

            <button type="submit" class="btn btn-primary">Sign Up</button>
        
        <div class="login">
            <p>Already registered? <a asp-controller="Login" asp-action="Teacher">Log In</a></p>
        </div>

        </form>
    </div>
        
</div>


</body>
</html>