Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using onlineexamproject.Data;
using onlineexamproject.Models;

namespace onlineexamproject.Controllers
{
    public class CourseController : BaseController
    {
        private readonly IConfiguration _configuration;

        public CourseController(IConfiguration configuration)
        {
            this._configuration = configuration;
        }

        // GET: Course
        public IActionResult Index()
        {
            DataTable dtbl = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("CourseAll", sqlConnection);
                sqlDa.SelectCommand.CommandType = CommandType.StoredProcedure;
                sqlDa.Fill(dtbl);
            }
            return View(dtbl);
        }

        // GET: Course/AddorEdit/
        public IActionResult AddorEdit(int? id)
        {
            Course course = new Course();
            if(id > 0)
            {
                course = FetchCourseById(id);
            }
            return View(course);
        }

        // POST: Course/AddorEdit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddorEdit(int id, [Bind("Course_Id,Course_Name,Course_Description")] Course course)
        {

            if (ModelState.IsValid)
            {
                using(SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
                {
                    sqlConnection.Open();
                    SqlCommand sqlCmd = new SqlCommand("CourseAddorEdit", sqlConnection);
                    sqlCmd.CommandType = CommandType.StoredProcedure;
                    sqlCmd.Parameters.AddWithValue("Course_Id", course.Course_Id);
                    sqlCmd.Parameters.AddWithValue("Course_Name", course.Course_Name);
                    sqlCmd.Parameters.AddWithValue("Course_Description", course.Course_Description);
                    sqlCmd.ExecuteNonQuery();
                }
               
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Course/Delete/5
        public IActionResult Delete(int? id)
        {
           Course course = FetchCourseById(id);
            return View(course);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                SqlCommand sqlCmd = new SqlCommand("CourseDeleteById", sqlConnection);
                sqlCmd.CommandType = CommandType.StoredProcedure;
                sqlCmd.Parameters.AddWithValue("Course_Id",id);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction(nameof(Index));
        }

        [NonAction]
        public Course FetchCourseById(int? id)
        {
             Course course = new Course();

            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                DataTable dtbl = new DataTable();
                sqlConnection.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("CourseById", sqlConnection);
                sqlDa.SelectCommand.CommandType = CommandType.StoredProcedure;
                sqlDa.SelectCommand.Parameters.AddWithValue("Course_Id", id);
                sqlDa.Fill(dtbl);
                if (dtbl.Rows.Count == 1)
                {
                    course.Course_Id = Convert.ToInt32(dtbl.Rows[0]["Course_Id"].ToString());
                    course.Course_Name = dtbl.Rows[0]["Course_Name"].ToString();
                    course.Course_Description = dtbl.Rows[0]["Course_Description"].ToString();

                }
                return course;
            }
        }
    }
}

Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using onlineexamproject.Data;
using onlineexamproject.Extensions;
using onlineexamproject.Models;

namespace onlineexamproject.Controllers
{
    public class ExamController : BaseController
    {

        private readonly ILogger<ExamController> _logger;
        private readonly IConfiguration _configuration;

        public ExamController(ILogger<ExamController> logger, IConfiguration configuration)
        {
            _logger = logger;
            this._configuration = configuration;
        } 


        // GET: Exam
        public IActionResult Index()
        {
            DataTable dtbl = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("ExamAll", sqlConnection);
                sqlDa.SelectCommand.CommandType = CommandType.StoredProcedure;
                sqlDa.Fill(dtbl);

            }
            return View(dtbl);
        }

       

        // GET: Exam/AddorEdit/
        public IActionResult AddorEdit(int? id)
        {
           Exam exam = new Exam();
            if(id > 0)
            {
                exam = FetchBookById(id);
            }
            return View(exam);
        }

        // POST: Exam/AddorEdit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddorEdit(int id, [Bind("ExamId,ExamName,ExamDateTime,Course_Id")] Exam exam)
        {
            if (ModelState.IsValid)
            {
                
                using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
                {
                    sqlConnection.Open();
                    SqlCommand sqlCmd = new SqlCommand("ExamAddorEdit", sqlConnection);
                    sqlCmd.CommandType = CommandType.StoredProcedure;
                    sqlCmd.Parameters.AddWithValue("ExamId", exam.ExamId);
                    sqlCmd.Parameters.AddWithValue("ExamName", exam.ExamName);
                    sqlCmd.Parameters.AddWithValue("ExamDateTime", exam.ExamDateTime);
                    sqlCmd.Parameters.AddWithValue("Course_Id", exam.Course_Id);
                    sqlCmd.ExecuteNonQuery();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(exam);
        }

        // GET: Exam/Delete/5
        public IActionResult Delete(int? id)
        {


            Exam exam = FetchBookById(id);

            return View(exam);
        }

        // POST: Exam/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlConnection.Open();
                SqlCommand sqlCmd = new SqlCommand("ExamDeleteById", sqlConnection);
                sqlCmd.CommandType = CommandType.StoredProcedure;
                sqlCmd.Parameters.AddWithValue("ExamId", id);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction(nameof(Index));
        }

        [NonAction]
        public Exam FetchBookById(int? id)
        {
            Exam exam= new Exam();
            using (SqlConnection sqlConnection = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                DataTable dtbl = new DataTable();
                sqlConnection.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("ExamById", sqlConnection);
                sqlDa.SelectCommand.CommandType = CommandType.StoredProcedure;
                sqlDa.SelectCommand.Parameters.AddWithValue("ExamId", id);
                sqlDa.Fill(dtbl);
                if (dtbl.Rows.Count == 1) 
                {
                    exam.ExamId = Convert.ToInt32(dtbl.Rows[0]["ExamId"].ToString());
                    exam.ExamName = dtbl.Rows[0]["ExamName"].ToString();
                    exam.ExamDateTime = Convert.ToDateTime(dtbl.Rows[0]["ExamDateTime"]);
                    exam.Course_Id = Convert.ToInt32(dtbl.Rows[0]["Course_Id"].ToString());
                }

                return exam;

            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult Attempt(int examId)
        {
            User? sessionUser = HttpContext.Session.GetObjectFromJson<User>("sessionUser");
            if (sessionUser == null)
            {
                return RedirectToAction("Student", "Login");
            }

            int student_Id = sessionUser.Id;
            return RedirectToRoute("exam", new { examId = examId });
        }

        public IActionResult Exam(int examId)
        {
            List<Questions> questionList = GetQuestions(examId);

            User? sessionUser = HttpContext.Session.GetObjectFromJson<User>("sessionUser");
            if (sessionUser == null)
            {
                return RedirectToAction("Student", "Login");
            }

            
            int userId = sessionUser.Id;

            ExamView examViewModel = new ExamView
            {
                Questions = questionList,
                StudentChoices = new List<StudentChoice>(),
                Student_Id = userId,
                ExamId = examId
            };

            return View(examViewModel);
        }

        public bool DeleteExistingAttempt(int student_Id, int examId)
        {
            string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True;";
            string query = "DELETE FROM StudentChoice WHERE Student_Id=@Student_Id AND ExamId=@ExamId;";

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        command.Parameters.AddWithValue("@Student_Id", student_Id);
                        command.Parameters.AddWithValue("@ExamId", examId);

                        int rowsAffected = command.ExecuteNonQuery();
                        Console.WriteLine(rowsAffected);
                        return rowsAffected > 0; // Return true if rows were deleted
                    }
                }
                catch (SqlException ex)
                {
                    Console.WriteLine(ex.ToString());
                    return false;
                }
            }
        }

        public List<Questions> GetQuestions(int examId)
        {
            List<Questions> questions = new List<Questions>();

            string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True;";
            string query = "SELECT * FROM Questions WHERE ExamId=@ExamId";

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        command.Parameters.AddWithValue("@ExamId", examId);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                int Q_Id = reader.GetInt32(reader.GetOrdinal("Q_Id"));
                                string Question = reader.GetString(reader.GetOrdinal("Question"));
                                string op_1 = reader.GetString(reader.GetOrdinal("op_1"));
                                string op_2 = reader.GetString(reader.GetOrdinal("op_2"));
                                string op_3 = reader.GetString(reader.GetOrdinal("op_3"));
                                string op_4 = reader.GetString(reader.GetOrdinal("op_4"));
                                string Correct_Answer = reader.GetString(reader.GetOrdinal("Correct_Answer"));

                                Questions question = new Questions(Q_Id, examId, Question, op_1, op_2, op_3, op_4, Correct_Answer);
                                questions.Add(question);
                            }
                        }
                    }
                }
                catch (SqlException ex)
                {
                    Console.WriteLine(ex.ToString());
                }
            }

            return questions;
        }

        public bool StoreStudentChoice(StudentChoice choice)
        {
            string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESS;Initial Catalog=exams;Integrated Security=True;";
            string query = @"
                INSERT INTO StudentChoice (Student_Id, ExamId, Q_Id, OptionSelected) 

Controllers/TeacherDashboardController.cs
using Microsoft.AspNetCore.Mvc;
using onlineexamproject.Extensions;
using onlineexamproject.Models;
using System.Data;
using System.Data.SqlClient;


namespace onlineexamproject.Controllers
{
    public class TeacherDashboardController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TeacherDashboard()
        {

            User? sessionUser = HttpContext.Session.GetObjectFromJson<User>("sessionUser");
            if (sessionUser == null)
            {
                return RedirectToAction("Teacher", "Login");
            }
            else if (sessionUser.Role == "Teacher")
            {
                List<Course> courses = new List<Course>();
                return View(courses);
            }
            return RedirectToAction("Teacher", "Login");



        }


       /* public List<Course> ViewCourseList()
        {
            string connectionString = "Data Source=LAPTOP-VLJVC05O\\SQLEXPRESSInitial Catalog=exams;Integrated Security=True;";
            List<Course> courses = new List<Course>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();

                    string query = "SELECT * FROM Course";
                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                Course course = new Course
                                {
                                    Course_Id = reader.GetInt32("Course_Id"),
                                    Course_Name = reader.GetString("Course_Name"),
                                    Course_Description = reader.GetString("Course_Description")
                                };
                                courses.Add(course);
                            }
                        }
                    }
                }
                catch (SqlException ex)
                {
                    Console.WriteLine(ex.ToString());
                }
            }
            return courses;
        }*/

    }

}

Views/TeacherDashboard/TeacherDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href='~/css/dashboard.css' rel='stylesheet'>

    <style>
        .form {
            width: 100%;
            margin-top: 20px;
            margin-left:50px;
            background: transparent;
            border-radius: 4px;
            font-size: 1rem;
            position: relative;
            border-color:black;
            border-radius: 15px;
            padding: 2em 2em 1em 2em;
            box-shadow: 0px 0px 10px 2px rgba(0,0,0,0.2);
            background-color: #D8EFD3;
            z-index:-1;
            padding-left:50px;
        }
    </style>
</head>

<body>
    <div class="head">
        <div class="side-nav">
            <img src="~/images/logo.png" height="50px" width="90px" />
            <div class="user">
                <img src="~/images/profile-pic.png" class="user-img">
                <div>
                    <strong>Username:</strong> @ViewBag.Username<br>
                    <strong>User ID:</strong> @ViewBag.Id
                </div>
                <img src="~/images/star.png" class="star-png">
            </div>
            <ul>
                <li class="hover"><img src="~/images/dashboard.png"><p><a asp-area="" asp-controller="TeacherDashboard" asp-action="TeacherDashboard" style="color: #F1F8E8; text-decoration:none">DashBoard</a></p></li>
                <li class="hover"><img src="~/images/course.png"><p><p><a asp-area="" asp-controller="Course" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Add Course</a></p></li>
                <li class="hover"><img src="~/images/exam.png"><p><a asp-area="" asp-controller="Exam" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Add Exam</a></p></li>
                <li class="hover"><img src="~/images/test.png"><p><a asp-area="" asp-controller="Questions" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Add Questions</a></p></li>
                <li class="hover"><img src="~/images/result.png"><p><a asp-area="" asp-controller="Result" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Result</a></p></li>
            </ul>

            <ul>
                <li style="color:white;"><img src="~/images/logout.png"><p><a asp-area="" asp-controller="Home" asp-action="Index" style="color: #F1F8E8; text-decoration:none">Log Out</a></p></li>
            </ul>
        </div>
        <div class="main-body">
            <div class="form">
            <p>
                    <h1 style="text-align:center"> Welcome to the Teacher Dashboard!</h1><br />
                    <h2 style="text-align:center" >Teacher Guidelines</h2><br />

                <h3>Adding Courses</h3><br/>

                <h4> 1.Navigate to Course Management</h4>
                 <p> - From the side navigation bar, select "Add Course"<br/>
                     - You will find an option to add courses"
                </p>

            <h4>2.Add Course Details</h4>
                <p>- Click on Create New<br/>
                - Fill in the required fields such as Course Name, Course Code and Description.<br/>
                - Click "Save" or "Submit" to add the course.<br/>
                - You may even edit or delete the added course from here if needed.<br/>
                </p><br /><br />

            <h3>Scheduling Exams</h3><br/>
            <h4> 1.Navigate to Exam Scheduling</h4>
               <p> - Go to the "Add Exams" section from the side bar.<br />
                - You will find an option to add exam
            </p>

            <h4> 2.Set Exam Details</h4>
               <p> - Click on Create New<br />
                - Enter the Exam Name, Date, Start/End Time, and the course id under which you want to add the exam.<br/>
                - Review the entered details.<br/>
                - Click "Save" to finalize the exam.<br/>
                - You may even edit or delete the added exam from here if needed.<br/>
                </p><br /><br />

            <h3>Scheduling Exams</h3><br/>



            <h4> 1.Navigate to Question Bank</h4>
               <p> - Go to the "Add Exams" section and select "Create New"</p>

            <h4> 2.Add Questions</h4>
               <p> - Enter the question text and provide answer options</p>

            <h4> 3.Save Questions</h4>
               <p> - Click "Add Question" after entering each question.<br/>
                - Similarly you can add all the questions in your exam.
            </p><br/><br/>

                <h3> General Tips</h3>

               <p>- Regularly Update Content: Ensure that all course materials and exam details are up-to-date.<br/>
                - Double-Check Entries: Review all entries for accuracy before saving.<br/>
                - Seek Help When Needed: If you encounter any issues, contact technical support.<br/>
            </p>
            </div>
        </div>
    </div>






    </div>
    </div>
</body>
</html>